linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  goimports:
    local-prefixes: github.com/lawzava/scrape
  govet:
    check-shadowing: true
  funlen:
    lines: 100
  misspell:
    locale: US
  nakedret:
    max-func-lines: 2
  gofumpt:
    extra-rules: true

linters:
  enable-all: true
  disable:
    - depguard

issues:
  exclude-rules:
    - path: examples/*
      linters:
        - gomnd
        - exhaustivestruct
        - gochecknoglobals
    - path: _test\.go
      linters:
        - exhaustivestruct
