project_name: scrape
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
 -
  env:
    - CGO_ENABLED=0
  main: ./*.go
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      386: i386
      amd64: x86_64
brews:
  - homepage: 'https://github.com/lawzava/scrape'
    description: 'CLI utility to scrape emails from websites'
    folder: Formula
    commit_author:
      name: Law Zava
      email: law@zava.dev
    tap:
      owner: lawzava
      name: scrape
